services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=cn334Admin
      - POSTGRES_PASSWORD=cn334Admin
    ports:
      - "5432:5432"
  user_api:
    build: ./user_service
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./user_service:/code
      - ./media:/code/media
    ports:
      - "3342:8888"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=cn334Admin
      - POSTGRES_PASSWORD=cn334Admin
    depends_on:
      - db
  front_end:
    build: ./app_frontend
    command: npm run dev
    volumes:
      - ./app_frontend:/app
      - /app/node_modules
    ports:
      - "3343:3000"
